sudo: false
dist: trusty
language: node_js
node_js: 8
addons:
  firefox: latest
  google-chrome: latest
install:
- npm install
- polymer install --variants
before_script:
# - gulp lint
- polymer lint --rules polymer-2-hybrid --input *.html
script:
- xvfb-run -s '-screen 0 1024x768x24' polymer test test/basic.html test/app-localize-behavior.html
  test/column.html test/column-group.html test/column-groups.html test/column-resizing.html
  test/column-reordering.html test/data-provider.html test/filtering.html --env saucelabs
- xvfb-run -s '-screen 0 1024x768x24' polymer test test/keyboard-navigation.html test/physical-count.html
  test/hidden-grid.html test/million-dollar-scrolling.html test/dynamic-item-size.html
  test/frozen-columns.html test/outer-scroller.html test/templates.html test/scrolling-mode.html
  test/row-height.html --env saucelabs
- xvfb-run -s '-screen 0 1024x768x24' polymer test test/row-details.html test/selecting.html
  test/style-scope.html test/array-data-provider.html test/sorting.html test/themability.html
  test/scroll-to-index.html test/resizing.html test/light-dom-observing.html test/doctype.html
  test/lazy-import.html --env saucelabs
- if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]];
  then npm i gemini@^4.0.0 gemini-sauce gemini-polyserve; gemini test test/visual;
  fi
after_success:
- cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls
notifications:
  slack:
    secure: TbelqQLsoEAgsDPDH6zcrsCKCgo1aUCIrBdJJPMS5cbRdHnuO9aVEyUjSSDwXKWaJF0wKGfD5p0PAFzEOCT4SfWGn0NijtJL7PacCl3DRn89NZTun+s86+uz8qzaPsw1LsyDlmq3ZZw0aNenYxg0xaYsaPUtsyx9/oHDQ8m6g1U2lmqUNAPOaJQpdshcrwhkxOCo7Axe8Gh+yJFGC5MiL5NQO1ncrVeKH4M0MZaSxQQJ4ifh0pc4gLxKCPH9ASHYrd89K+QXimKkGT2b2VCtpL9j4IBQwPdblUTnZDYZl8tNnA8z/baaXqTLvPwbZjhUO1nGhMYTn175zh3i1L1kPwkY5PtENiuM3CNANiy8xUpqyqulL3XQHA52wvPpECLg5DOLGtbDKTVIwF4M+NOL+Sg4WiAPwLU4o5QLjrRrWDcBLYubPBIjVW6bOuaIGezh74FcaAsV33KArw5Ml+aPNeI4dCcl2B+qctgRnHuEI86qPg+0dg+w1DRyZjH4t/IY5off8pgWpV+8T6LPzrAIz+ERuEO4dUvyF3rEV2mqYsnxq6/q/Pt0nSzVmxpVZeS375jaZJXTj1JprKbTuaG5z87CgNTloRG3Dn0ceQ4phwvwet+Hae7NndfIjG/PGBx4b38akMSPE/md/nHliqxFqAQpD22F1Bmi7MzIlBYxNAM=
after_failure:
- after_failure
