name: Unit Tests

# all pull requests
on: pull_request

jobs:
# Running local tests is disabled due to outdated dependencies
# see https://github.com/vaadin/components-team-tasks/issues/628
#  unit-tests-p2:
#    name: Polymer 2 on the CI agent
#    runs-on: ubuntu-latest
#    steps:
#      - name: Set up Node 16.x
#        uses: actions/setup-node@v4
#        with:
#          node-version: 16.x
#
#      - name: Check out the source code
#        uses: actions/checkout@v2
#
#      - name: Install global npm dependencies
#        # bower is needed to run 'bower install'
#        # polymer-cli is needed to run the lint step
#        run: "npm install --quiet --no-progress --global bower polymer-cli"
#
#      - name: Install project npm dependencies
#        run: "npm ci"
#
#      - name: Install project Bower dependencies
#        run: "bower install --quiet"
#
#      - name: Run automated magi-cli checks
#        run: "npm run check"
#
#      - name: Run a linter
#        run: "npm run lint"
#
#      # the full set of environments is tested with Polymer 3 below
#      - name: Run unit tests locally (in the VM instance running this job)
#        run: "xvfb-run -s '-screen 0 1024x768x24' npm test"

  unit-tests-p3:
    name: Polymer 3 on SauceLabs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x

      - name: Check out the (Polymer 2) source code
        uses: actions/checkout@v2

      - name: Install global npm dependencies
        # bower and polymer-modulizer are needed to run the Polymer 3 conversion step
        run: "npm install --quiet --no-progress --global bower magi-cli polymer-modulizer"

      - name: Convert the source code to Polymer 3
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          magi p3-convert --out . --import-style=name

      # workaround for running tests on Android on SauceLabs (see wct.conf.js)
      - name: Add 'localhost-for-saucelabs' to /etc/hosts
        run: echo "127.0.0.1 localhost-for-saucelabs" | sudo tee -a /etc/hosts

      - name: Run unit tests [Desktop / Batch 1]
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm test -- --env saucelabs --suites batch1

      - name: Run unit tests [Desktop / Batch 2]
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm test -- --env saucelabs --suites batch2

      - name: Run unit tests [Desktop / Batch 3]
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm test -- --env saucelabs --suites batch3

      - name: Run unit tests [Desktop / Batch 4]
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm test -- --env saucelabs --suites batch4

      - name: Run unit tests [Desktop / Batch 5]
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
        run: npm test -- --env saucelabs --suites batch5
